### ISSUE TITLE
Several warnings in developer mode

### ISSUE THREAD

**Issue by iv-enovation** [developerck/moodle-local_enrolstats#1]
There are several notices and warnings when the full developer debug mode enabled

1:
Unknown table specified in objecttable field

    line 786 of /lib/classes/event/base.php: call to debugging()
    line 808 of /lib/classes/event/base.php: call to core\event\base->validate_before_trigger()
    line 81 of /local/enrolstats/index.php: call to core\event\base->trigger()

Since the plugin does not require any DB tables, the table should not be specified in enrolstats_view::init(). This warning is easily fixed by removing "$this->data['objecttable'] = 'local_enrolstats';" from init() in enrolstats/classes/event/enrolstats_view.php

2:
Class 'coursecat' has been renamed for the autoloader and is now deprecated. Please use 'core_course_category' instead.

    line 137 of /lib/classes/component.php: call to debugging()
    line ? of unknownfile: call to core_component::classloader()
    line 88 of /local/enrolstats/index.php: call to spl_autoload_call()

As it says, "coursecat" should be simply renamed to in "core_course_category" enrolstats/index.php:
$courses = core_course_category::get($categoryid)->get_courses($options);
$coursecount = core_course_category::get($categoryid)->get_courses_count(array('recursive' => true));

ADDITIONALLY: there is also no need to include coursecatlib.php, so the line:
require_once($CFG->libdir . '/coursecatlib.php');
can be simply removed

3:
Notice: Undefined variable: m in /var/www/html/ticket/moodle_38/local/enrolstats/index.php on line 137

$m should be checked for existence and optionally reinitiated, e.g. $m = isset($m)?$m:'';

4:
in index.php the oage URL is most probably not right:
    $PAGE->set_url(new moodle_url('/local/aac/enrols.php'));
Similarly later,
    $select = new single_select(new moodle_url('/local/aac/enrols.php'), 'categoryid',

**Comment by developerck** [comment]
thanks @iv-enovation for the points as well as their solution.
i updated the code a little bit except point 2 as i was thinking to support the old codebase.  i have this in my loop to make it version wise.

point 4 was updated 21 days back

**Comment by iv-enovation** [comment]
Thanks, 

Please also check the plugin review issue https://tracker.moodle.org/browse/CONTRIB-8146

Best regards,
Ivan

**Comment by developerck** [comment]
Thanks @iv-enovation 

I have updated with one more slight changes. and updated the ticket as well.

**Comment by iv-enovation** [comment]
Hi 
There still is an issue with /index.php lines 87 and 88:
$courses = coursecat::get($categoryid)->get_courses($options);
$coursecount = coursecat::get($categoryid)->get_courses_count(array('recursive' => true));

it generates a warning: 
"Class 'coursecat' has been renamed for the autoloader and is now deprecated. Please use 'core_course_category' instead.<ul style="text-align: left" data-rel="backtrace"><li>line 137 of /lib/classes/component.php: call to debugging()</li><li>line ? of unknownfile: call to core_component::classloader()</li><li>line 87 of /local/enrolstats/index.php: call to spl_autoload_call()"</ul>

so it should be enough just to rename coursecat::get() to core_course_category::get()

AND: when selecting a category from the dropdown list, there's an error:
"Coding error detected, it must be fixed by a programmer: objecttable must be specified in init() method if objectid present"
That's because in index.php a category id is passed to $params as 'objectid':
'objectid' => $categoryid,
If it's the desired functionality, the "objecttable" in init() in enrolstats/classes/event/enrolstats_view.php hsould be set to the category table

**Comment by developerck** [comment]
Thanks Ivan,

Please excuse me for this Issue.
I have done the fixes and unit-tested that before marking.

I am closing this. feel free to reopen.
Thanks Again.
