### ISSUE TITLE
incorrect camel case in lang strings.

### ISSUE THREAD

**Issue by danmarsden** [developerck/moodle-local_enrolstats#2]
Moodle uses sentence case - please check your lang strings as some use camel case.

for example strings like:
$string['mystring'] = "My String";
should be:
$string['mystring'] = "My string";

Note: this is not a blocker for approval in the plugins db.

**Comment by developerck** [comment]
yes, I did the change where the string is sentence or phrase, however, some are heading level representation, so i had to kept them in same way.

Thank you.
