### ISSUE TITLE
hard-coded english strings

### ISSUE THREAD

**Issue by danmarsden** [developerck/moodle-local_enrolstats#3]
eg:
https://github.com/developerck/moodle-local_enrolstats/blob/master/index.php#L129
 Active  Suspended

https://github.com/developerck/moodle-local_enrolstats/blob/master/index.php#L96
"select"

please review all your strings and make sure they are stored within the lang file rather than hard-coded.

this is a blocker for plugins db approval.

**Comment by developerck** [comment]
Thanks Dan,

All string has been corrected and placed into lang file.

**Comment by danmarsden** [comment]
doesn't look like you've sorted them all yet...
I can see hard-coded strings in the table->head and the text "suspended" hard-coded in the file instead of in the lang strings... can you please take a close look through your code to see if there are any others?

thanks!
