### ISSUE TITLE
missing privacy api string.

### ISSUE THREAD

**Issue by danmarsden** [developerck/moodle-local_enrolstats#5]
If you view the privacy api report under admin > users > privacy and policies > "plugin privacy registry" I'd expect to see a missing string in your plugin for privacy:metadata

**Comment by developerck** [comment]
Hi Dan,

Thanks for your feedback.

I have added that.
$string['privacy:metadata'] = 'The "Enrolment Stats Plugin" only displays existing data and does not store any user data.';
